---
############################################################
#  tasks file to configure Openstack
############################################################
- name: Config cloud block
  include_tasks: cloud_config_deploy.yml
  loop: "{{ clouds | dict2items }}"
  loop_control:
    loop_var: ii_cloud
    label: "{{ ii_cloud.key }}"
  when: (clouds is defined) and
        ((ii_cloud.value.faikolla_srv is not defined) or (ii_cloud.value.faikolla_srv == inventory_hostname_short))
