---
############################################################
#  tasks file to admin Openstack
############################################################
- name: Admin cloud block
  include_tasks: os_domains_deploy.yml
  loop: "{{ clouds | dict2items }}"
  loop_control:
    loop_var: ii_cloud
    label: "{{ ii_cloud.key }}"
  when: (clouds is defined)
