---
############################################################
#  tasks file for removing all entities from openstack
############################################################
- name: List current os domains
  vars:
    openstack_client_command: "domain list"
    cli_result: 'yes'
  include_tasks: "os_client.yml"

- name: Make os domains list
  set_fact:
    os_domain_list: "{{ osclient_result | kemopq.freeipa_kolla.os_domain_list }}"

- name: Delete os domains loop
  include_tasks: "os_domain_delete.yml"
  when: openstack_domains is defined
  loop: "{{ openstack_domains | dict2items }}"
  loop_control:
    loop_var: ii_domain
    label: "{{ ii_domain.key }}"
