---
############################################################
#  tasks file for creating openstack project with groups
############################################################
- name: Create os project "{{ ii_project.key }}"
  vars:
    openstack_client_command:
      "project create --description 'FreeIPACreated' --domain {{ ii_domain.key }} {{ ii_project.key }}"
    cli_result: 'no'
  include_tasks: "os_client.yml"
  when: ii_project.key not in os_project_list

- name: Adding os roles to groups loop
  include_tasks: "os_group_role_add.yml"
  when: ii_project.value.freeipa_groups is defined
  loop: "{{ ii_project.value.freeipa_groups | dict2items }}"
  loop_control:
    loop_var: ii_group
    label: "{{ ii_group.key }}"
