---
# FORWARDERS
# Global forwarders
global_forwarders:
  - policy: 'first'      # only/first
    forwarders:
      - ip: '10.1.2.3'
        # port: '56'

# Zone forwarders
# zone_forwarders:
#   - zone: 'iskratel.mak'
#     policy: 'only'      # only/first
#     forwarders:
#       - ip: '172.18.138.129'
#         # port: '56'

# DNSSEC
dnssec_disable: 'yes'

# default IPA users and groups
freeipa_servers:
  - "freeipa-server-node1.{{ ipaserver_domain }}"

freeipa_groups:
  osadmins:
    desc: "Openstack admin group"
  osmembers:
    desc: "Openstack member group"

freeipa_users:
  keyadmin:
    first: "Keystone"
    last: "Backend"
    password: "kp1234"
  osadmin:
    first: "OsAdmin"
    last: "Admin"
    password: "kp1234"
    group:
      - osadmins
  osmember:
    first: "OsMember"
    last: "Member"
    password: "kp1234"
    group:
      - osmembers

# openstack
openstack_domains:
  kemopq_domain:
    description: "Creted by FreeIPA install script"
    openstack_projects:
      kemopq_project:
        description: "Creted by FreeIPA install script"
        freeipa_groups:
          osadmins:
            openstack_role: "admin"
          osmembers:
            openstack_role: "_member_"
      kemopq_project_add:
        description: "Creted by FreeIPA install script"
        freeipa_groups:
          osmembers:
            openstack_role: "admin"

clouds:
  vmcloud1:
    faikolla_srv: "faikolla1-node1"
    openstack_conf_path: "/opt/cloud-cfg/vmcloud1/config"  # location of configuration overrides (node_custom_config in kolla ansible globals.yml)
    public_ip: "192.168.100.19"
    public_name: "vmcloud1"
    public_int_tls: "no"
    admin_passwd: "iskratel"
  vmcloud2:
    faikolla_srv: "faikolla2-node1"
    openstack_conf_path: "/opt/cloud-cfg/vmcloud2/config"
    public_ip: "192.168.26.60"
    public_name: "vmcloud2"
    public_int_tls: "no"
    admin_passwd: "mypassword"
