---
# IPA
freeipa_servers:                   # list of IPA servers (FQDNs)
  - "freeipa-server-node1.example.test"

# predefined IPA groups
freeipa_groups:
  osadmins:
    desc: "Openstack admin group"
  osmembers:
    desc: "Openstack member group"

# predefined IPA users
freeipa_users:
  keyadmin:
    first: "Keystone"
    last: "Backend"
    password: "kp1234"
  osadmin:
    first: "OsAdmin"
    last: "Admin"
    password: "kp1234"
    group:
      - osadmins
  osmember:
    first: "OsMember"
    last: "Member"
    password: "kp1234"
    group:
      - osmembers

# openstack
openstack_conf_path: "/opt/etc-kolla/vmcloud/config"  # location of configuration overrides (node_custom_config in kolla ansible globals.yml)

# list of openstack domains with projects and associated user groups (defined in IPA)
openstack_domains:
  kemopq_domain:
    description: "Creted by FreeIPA install script"
    openstack_projects:
      kemopq_project:
        description: "Creted by FreeIPA install script"
        freeipa_groups:
          osadmins:
            openstack_role: "admin"
          osmembers:
            openstack_role: "_member_"
      kemopq_project_add:
        description: "Creted by FreeIPA install script"
        freeipa_groups:
          osmembers:
            openstack_role: "admin"

openstack_url: "http://192.168.100.19"    # Openstack API URL
openstack_user_password: "iskratel"       # admin user password
