---
# FORWARDERS
# Global forwarders
global_forwarders:
  - policy: 'first'      # only/first
    forwarders:
      - ip: '10.1.2.3'
        # port: '56'

# Zone forwarders
# zone_forwarders:
#   - zone: 'iskratel.mak'
#     policy: 'only'      # only/first
#     forwarders:
#       - ip: '172.18.138.129'
#         # port: '56'

# DNSSEC
dnssec_disable: 'yes'

# default IPA users and groups
freeipa_groups:
  osadmins:
    desc: "Openstack admin group"
  osmembers:
    desc: "Openstack member group"

freeipa_users:
  keyadmin:
    first: "Keystone"
    last: "Backend"
    password: "kp1234"
  osadmin:
    first: "OsAdmin"
    last: "Admin"
    password: "kp1234"
    group:
      - osadmins
  osmember:
    first: "OsMember"
    last: "Member"
    password: "kp1234"
    group:
      - osmembers

# openstack
openstack_domains:
  kemopq_domain:
    description: "Creted by FreeIPA install script"
    openstack_projects:
      kemopq_project:
        description: "Creted by FreeIPA install script"
        freeipa_groups:
          osadmins:
            openstack_role: "admin"
          osmembers:
            openstack_role: "_member_"
      kemopq_project_add:
        description: "Creted by FreeIPA install script"
        freeipa_groups:
          osmembers:
            openstack_role: "admin"

ipa_integration_params:
  ipa_servers:
    - ipasrv1
  keystone_ipa_admin_user: "keyadmin"
  keystone_ipa_admin_password: "kp1234"
